
/*
 * This file was automatically generated by sdbus-c++-xml2cpp; DO NOT EDIT!
 */

#ifndef __sdbuscpp__include_grabber_linux_pipewire_RemoteDesktopProxy_h__proxy__H__
#define __sdbuscpp__include_grabber_linux_pipewire_RemoteDesktopProxy_h__proxy__H__

#include <sdbus-c++/sdbus-c++.h>
#include <string>
#include <tuple>

namespace org {
namespace freedesktop {
namespace portal {

class RemoteDesktop_proxy
{
public:
    static constexpr const char* INTERFACE_NAME = "org.freedesktop.portal.RemoteDesktop";

protected:
    RemoteDesktop_proxy(sdbus::IProxy& proxy)
        : m_proxy(proxy)
    {
    }

    RemoteDesktop_proxy(const RemoteDesktop_proxy&) = delete;
    RemoteDesktop_proxy& operator=(const RemoteDesktop_proxy&) = delete;
    RemoteDesktop_proxy(RemoteDesktop_proxy&&) = delete;
    RemoteDesktop_proxy& operator=(RemoteDesktop_proxy&&) = delete;

    ~RemoteDesktop_proxy() = default;

    void registerProxy()
    {
    }

public:
    sdbus::ObjectPath CreateSession(const std::map<std::string, sdbus::Variant>& options)
    {
        sdbus::ObjectPath result;
        m_proxy.callMethod("CreateSession").onInterface(INTERFACE_NAME).withArguments(options).storeResultsTo(result);
        return result;
    }

    sdbus::ObjectPath SelectDevices(const sdbus::ObjectPath& session_handle, const std::map<std::string, sdbus::Variant>& options)
    {
        sdbus::ObjectPath result;
        m_proxy.callMethod("SelectDevices").onInterface(INTERFACE_NAME).withArguments(session_handle, options).storeResultsTo(result);
        return result;
    }

    sdbus::ObjectPath Start(const sdbus::ObjectPath& session_handle, const std::string& parent_window, const std::map<std::string, sdbus::Variant>& options)
    {
        sdbus::ObjectPath result;
        m_proxy.callMethod("Start").onInterface(INTERFACE_NAME).withArguments(session_handle, parent_window, options).storeResultsTo(result);
        return result;
    }

    void NotifyPointerMotion(const sdbus::ObjectPath& session_handle, const std::map<std::string, sdbus::Variant>& options, const double& dx, const double& dy)
    {
        m_proxy.callMethod("NotifyPointerMotion").onInterface(INTERFACE_NAME).withArguments(session_handle, options, dx, dy);
    }

    void NotifyPointerMotionAbsolute(const sdbus::ObjectPath& session_handle, const std::map<std::string, sdbus::Variant>& options, const uint32_t& stream, const double& x, const double& y)
    {
        m_proxy.callMethod("NotifyPointerMotionAbsolute").onInterface(INTERFACE_NAME).withArguments(session_handle, options, stream, x, y);
    }

    void NotifyPointerButton(const sdbus::ObjectPath& session_handle, const std::map<std::string, sdbus::Variant>& options, const int32_t& button, const uint32_t& state)
    {
        m_proxy.callMethod("NotifyPointerButton").onInterface(INTERFACE_NAME).withArguments(session_handle, options, button, state);
    }

    void NotifyPointerAxis(const sdbus::ObjectPath& session_handle, const std::map<std::string, sdbus::Variant>& options, const double& dx, const double& dy)
    {
        m_proxy.callMethod("NotifyPointerAxis").onInterface(INTERFACE_NAME).withArguments(session_handle, options, dx, dy);
    }

    void NotifyPointerAxisDiscrete(const sdbus::ObjectPath& session_handle, const std::map<std::string, sdbus::Variant>& options, const uint32_t& axis, const int32_t& steps)
    {
        m_proxy.callMethod("NotifyPointerAxisDiscrete").onInterface(INTERFACE_NAME).withArguments(session_handle, options, axis, steps);
    }

    void NotifyKeyboardKeycode(const sdbus::ObjectPath& session_handle, const std::map<std::string, sdbus::Variant>& options, const int32_t& keycode, const uint32_t& state)
    {
        m_proxy.callMethod("NotifyKeyboardKeycode").onInterface(INTERFACE_NAME).withArguments(session_handle, options, keycode, state);
    }

    void NotifyKeyboardKeysym(const sdbus::ObjectPath& session_handle, const std::map<std::string, sdbus::Variant>& options, const int32_t& keysym, const uint32_t& state)
    {
        m_proxy.callMethod("NotifyKeyboardKeysym").onInterface(INTERFACE_NAME).withArguments(session_handle, options, keysym, state);
    }

    void NotifyTouchDown(const sdbus::ObjectPath& session_handle, const std::map<std::string, sdbus::Variant>& options, const uint32_t& stream, const uint32_t& slot, const double& x, const double& y)
    {
        m_proxy.callMethod("NotifyTouchDown").onInterface(INTERFACE_NAME).withArguments(session_handle, options, stream, slot, x, y);
    }

    void NotifyTouchMotion(const sdbus::ObjectPath& session_handle, const std::map<std::string, sdbus::Variant>& options, const uint32_t& stream, const uint32_t& slot, const double& x, const double& y)
    {
        m_proxy.callMethod("NotifyTouchMotion").onInterface(INTERFACE_NAME).withArguments(session_handle, options, stream, slot, x, y);
    }

    void NotifyTouchUp(const sdbus::ObjectPath& session_handle, const std::map<std::string, sdbus::Variant>& options, const uint32_t& slot)
    {
        m_proxy.callMethod("NotifyTouchUp").onInterface(INTERFACE_NAME).withArguments(session_handle, options, slot);
    }

    sdbus::UnixFd ConnectToEIS(const sdbus::ObjectPath& session_handle, const std::map<std::string, sdbus::Variant>& options)
    {
        sdbus::UnixFd result;
        m_proxy.callMethod("ConnectToEIS").onInterface(INTERFACE_NAME).withArguments(session_handle, options).storeResultsTo(result);
        return result;
    }

public:
    uint32_t AvailableDeviceTypes()
    {
        return m_proxy.getProperty("AvailableDeviceTypes").onInterface(INTERFACE_NAME).get<uint32_t>();
    }

    uint32_t version()
    {
        return m_proxy.getProperty("version").onInterface(INTERFACE_NAME).get<uint32_t>();
    }

private:
    sdbus::IProxy& m_proxy;
};

}}} // namespaces

#endif
