#!/bin/sh
echo "Preparing to uninstall HyperHDR"
FOUND_USR=`who | grep -o -m1 '^\w*\b'` || "root"
HYPERHDR_RUNNING=false
pgrep hyperhdr > /dev/null 2>&1 && HYPERHDR_RUNNING=true

if grep -m1 systemd /proc/1/comm > /dev/null; then
    $HYPERHDR_RUNNING && systemctl stop hyperhdr"@${FOUND_USR}" 2> /dev/null
    systemctl -q disable hyperhdr"@${FOUND_USR}" 2>/dev/null
    systemctl daemon-reload 2>/dev/null || true
fi
killall hyperhdr 2> /dev/null
exit 0
