name: ðŸž Bug Report
description: Report an issue with HyperHDR
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ### ðŸ›¡ï¸ SECURITY & PRIVACY FIRST
        **IMPORTANT:** Before posting any logs or screenshots, **sanitize your data**. 
        Remove any:
        * **API Tokens/Keys** (e.g., Philips Hue, WLED, Home Assistant, etc.)
        * **Passwords or Credentials**
        * **Private Network Details** (if you consider them sensitive)
        
        *Your logs are public. It is your responsibility to remove private information.*

        ### ðŸ§ª TEST LATEST VERSION FIRST
        Before reporting, please check the **latest Github Actions/beta builds**. The issue might already be fixed there!        

  - type: textarea
    id: reproduction-path
    attributes:
      label: Detailed Reproduction Path
      description: Describe exactly how the error occurred. Provide a step-by-step path. If it happens randomly also try to provide a context.
      placeholder: "1. Open HyperHDR, 2. Go to 'X' tab, 3. Change setting 'Y' to..."
    validations:
      required: true
      min_length: 30

  - type: dropdown
    id: tested-beta
    attributes:
      label: Have you tested the latest Github Action/beta build?
      description: We strongly recommend testing the latest dev build before reporting.
      options:
        - "Yes, the problem still exists in the latest beta/Github Action builds"
        - "No, I am only using the official stable release"
    validations:
      required: true

  - type: dropdown
    id: previous-version
    attributes:
      label: Did this work in a previous stable version?
      options:
        - "Yes, it worked in the previous version"
        - "No, it never worked for me"
        - "N/A (This is a new feature)"
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Select your hardware platform
      options:
        - "Raspberry Pi Zero 2 W (your grabber may be affected by the V4L2 kernel bug)"
        - "Raspberry Pi 3 (your grabber may be affected by the V4L2 kernel bug)"
        - "Raspberry Pi 4"
        - "Raspberry Pi 5"
        - "Windows (x64)"
        - "Linux (x64:  Ubuntu/Debian/Fedora/Arch)"
        - "Linux (arm64)"
        - "macOS"
        - "webOS (remember that we do not handle webOS builds)"
    validations:
      required: true

  - type: dropdown
    id: grabber
    attributes:
      label: Capture Device / Grabber
      description: Which grabber or software capture method are you using?
      options:
        - Pipewire (Software)
        - DirectX11 (Software)
        - Flatbuffers/Protobuffers (Software)        
        - MS2109 (USB)
        - MS2130 (USB)
        - UGREEN 25173 (USB)
        - Other USB Grabber (provide model in the "Detailed Reproduction Path")
        - Other software Grabber (provide type in the "Detailed Reproduction Path")        
        - Not applicable
    validations:
      required: true

  - type: dropdown
    id: led-driver
    attributes:
      label: LED Driver
      description: Which main LED driver is selected in the configuration?
      options:
        - HyperSerialPico
        - HyperSerialSpi        
        - HyperSerialESP32
        - WLED
        - Neopixel WS281x/SK6812 (GPIO/FTDI)
        - DotStart APA102/SK9822 (GPIO/FTDI)
        - Philips Hue
        - Adalight
        - Skydimo
        - Other
    validations:
      required: true

  - type: textarea
    id: system-about
    attributes:
      label: System About Info
      description: Paste the content of the 'Advanced' -> 'About' system configuration tab here.
      placeholder: "If the WebUI does not start, type: 'GUI not accessible'"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Application Log
      description: |
        Logs must refer to the issue and be taken in its entirety after approx. 2-3 minutes of runtime.
        If the application doesn't start: run it from the command line (on Windows use the `-c` parameter) and copy the output from the terminal.
        Accepted links: PrivateBin, Pastebin, Hastebin, mPaste.
      placeholder: "Paste your sanitized logs here or provide a link..."
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Validation Check
      options:
        - label: I understand that my issue will be automatically closed if logs are missing/incomplete or description is insufficient.
          required: true
