name: 🐞 Bug Report
description: Report an issue with HyperHDR
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        #### 🛡️ SECURITY & PRIVACY FIRST
        <p align="left">
          <small><b>IMPORTANT:</b> Before posting any logs or screenshots, <b>sanitize your data</b>.</small><br>
          <small>Remove any: API Tokens/Keys (Hue, WLED, HA, etc.), Passwords, or Private Network Details.</small><br>
          <small><i>Your logs are public. It is your responsibility to remove private information.</i></small>
        </p>

        #### 🧪 USE SEARCH AND TEST LATEST VERSION FIRST
        <p align="left">
          <small>Please <b>search existing <a href="https://wiki.hyperhdr.eu/FAQ">FAQ</a>, Github Issues and Discussions</b> to see if this has been reported.<br>Also, check the <b>latest Github Actions/beta builds</b> – the issue might already be fixed there.</small>
        </p>

  - type: textarea
    id: reproduction-path
    attributes:
      label: Detailed Reproduction Path
      description: Describe exactly how the error occurred. Provide a step-by-step path. If it happens randomly also try to provide a context.
      placeholder: "1. Open HyperHDR, 2. Go to 'X' tab, 3. Change setting 'Y' to..."
    validations:
      required: true
      min_length: 30

  - type: dropdown
    id: tested-beta
    attributes:
      label: Have you tested the latest Github Action/beta build?
      description: We strongly recommend testing the latest dev build before reporting.
      options:
        - "..."
        - "Yes, the problem still exists in the latest beta/Github Action builds"
        - "No, I am only using the official stable release"
    validations:
      required: true

  - type: dropdown
    id: previous-version
    attributes:
      label: Did this work in a previous stable version?
      options:
        - "..."
        - "Yes, it worked in the previous version"
        - "No, it never worked for me"
        - "N/A (This is a new feature)"
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Select your hardware platform
      options:
        - "..."
        - "Windows"
        - "Raspberry Pi 5"
        - "Raspberry Pi 4"
        - "Raspberry Pi 3 (your grabber may be affected by the V4L2 kernel bug)"
        - "Raspberry Pi Zero 2 W (your grabber may be affected by the V4L2 kernel bug)"
        - "Linux (x64:  Ubuntu/Debian/Fedora/Arch)"
        - "Linux (arm64)"
        - "macOS"
        - "webOS (please note: we do not provide official webOS installers)"
    validations:
      required: true

  - type: dropdown
    id: grabber
    attributes:
      label: Capture Device / Grabber
      description: Which grabber or software capture method are you using?
      options:
        - "..."
        - MS2109 (USB)
        - MS2130 (USB)
        - UGREEN 25173 (USB)
        - Pipewire (Software)
        - DirectX11 (Software)
        - Flatbuffers/Protobuffers (Software)        
        - Other software capture (provide type in the "Detailed Reproduction Path")
        - Other USB Grabber (provide model in the "Detailed Reproduction Path")        
        - Not applicable
    validations:
      required: true

  - type: dropdown
    id: led-driver
    attributes:
      label: LED Driver
      description: Which main LED driver is selected in the configuration?
      options:
        - "..."
        - HyperSerialPico
        - HyperSerialSpi        
        - HyperSerialESP32
        - WLED
        - Neopixel WS281x/SK6812 (GPIO/FTDI)
        - DotStart APA102/SK9822 (GPIO/FTDI)
        - Philips Hue
        - Adalight
        - Skydimo
        - Other
    validations:
      required: true

  - type: textarea
    id: system-about
    attributes:
      label: System About Info
      description: "Paste the content of the 'Advanced' -> 'About HyperHDR' system configuration tab here."
      placeholder: "If the WebUI does not start, type: 'GUI not accessible'"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Application Log
      description: |
        Logs must be relevant to the issue and provided in full after approx. 2-3 minutes of runtime or immediately after the error occurs.<br>
        If the application doesn't start: run it from the command line (use the <code>-c</code> parameter on Windows) and copy the output.<br>
        <b>Accepted links:</b> PrivateBin, Pastebin, Hastebin, mPaste.<br>
      placeholder: "Paste your sanitized logs here or provide a link..."
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Validation Check
      options:
        - label: I understand that my issue will be automatically closed if logs are missing/incomplete or description is insufficient.
          required: true
