/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "message.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(proto_HyperhdrRequest, proto_HyperhdrRequest, AUTO)


PB_BIND(proto_ColorRequest, proto_ColorRequest, AUTO)


PB_BIND(proto_ImageRequest, proto_ImageRequest, AUTO)


PB_BIND(proto_ClearRequest, proto_ClearRequest, AUTO)


PB_BIND(proto_HyperhdrReply, proto_HyperhdrReply, AUTO)


/* Definition for extension field proto_ColorRequest_colorRequest */
typedef struct _proto_ColorRequest_colorRequest_extmsg {
    proto_ColorRequest colorRequest;
} proto_ColorRequest_colorRequest_extmsg;
#define proto_ColorRequest_colorRequest_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  colorRequest,     10)
#define proto_ColorRequest_colorRequest_extmsg_CALLBACK NULL
#define proto_ColorRequest_colorRequest_extmsg_DEFAULT NULL
#define proto_ColorRequest_colorRequest_extmsg_colorRequest_MSGTYPE proto_ColorRequest
pb_byte_t proto_ColorRequest_colorRequest_extmsg_default[] = {0x00};
PB_BIND(proto_ColorRequest_colorRequest_extmsg, proto_ColorRequest_colorRequest_extmsg, AUTO)
const pb_extension_type_t proto_ColorRequest_colorRequest = {
    NULL,
    NULL,
    &proto_ColorRequest_colorRequest_extmsg_msg
};

/* Definition for extension field proto_ImageRequest_imageRequest */
typedef struct _proto_ImageRequest_imageRequest_extmsg {
    proto_ImageRequest imageRequest;
} proto_ImageRequest_imageRequest_extmsg;
#define proto_ImageRequest_imageRequest_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  imageRequest,     11)
#define proto_ImageRequest_imageRequest_extmsg_CALLBACK NULL
#define proto_ImageRequest_imageRequest_extmsg_DEFAULT NULL
#define proto_ImageRequest_imageRequest_extmsg_imageRequest_MSGTYPE proto_ImageRequest
pb_byte_t proto_ImageRequest_imageRequest_extmsg_default[] = {0x00};
PB_BIND(proto_ImageRequest_imageRequest_extmsg, proto_ImageRequest_imageRequest_extmsg, AUTO)
const pb_extension_type_t proto_ImageRequest_imageRequest = {
    NULL,
    NULL,
    &proto_ImageRequest_imageRequest_extmsg_msg
};

/* Definition for extension field proto_ClearRequest_clearRequest */
typedef struct _proto_ClearRequest_clearRequest_extmsg {
    proto_ClearRequest clearRequest;
} proto_ClearRequest_clearRequest_extmsg;
#define proto_ClearRequest_clearRequest_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  clearRequest,     12)
#define proto_ClearRequest_clearRequest_extmsg_CALLBACK NULL
#define proto_ClearRequest_clearRequest_extmsg_DEFAULT NULL
#define proto_ClearRequest_clearRequest_extmsg_clearRequest_MSGTYPE proto_ClearRequest
pb_byte_t proto_ClearRequest_clearRequest_extmsg_default[] = {0x00};
PB_BIND(proto_ClearRequest_clearRequest_extmsg, proto_ClearRequest_clearRequest_extmsg, AUTO)
const pb_extension_type_t proto_ClearRequest_clearRequest = {
    NULL,
    NULL,
    &proto_ClearRequest_clearRequest_extmsg_msg
};




