name: Cache clearing action after closing PR
run-name: Cache clearing

on:
  pull_request:
    types:
      - closed

jobs:
  clean_PR_ccache:
    name: Delete old CCache files
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - run: gh cache delete --all --ref "refs/heads/${{ github.head_ref }}" --repo ${{ github.repository }}
        env:
          GH_TOKEN: ${{ github.token }}
  clean_PR_artifacts:
    name: Delete old Artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: stefanluptak/delete-old-pr-artifacts@v1
        with:
          workflow_filename: push-master.yml
          debug: true
