name: Cache clear action on PR close

on:
  pull_request:
    types:
      - closed

jobs:
  clean_PR_ccache:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: yumemi-inc/clean-cache-action@v1
        with:
          ref: 'refs/pull/${{ github.event.pull_request.number }}/merge'
  clean_PR_artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: stefanluptak/delete-old-pr-artifacts@v1
        with:
          workflow_filename: push-master.yml
          debug: true
